# Evaluating Tidally Induced Acceleration as a Novel Cause of the Lunar Crustal Asymmetry

Author: Kas Knicely (she|her)
Date of Creation: 2026 March 17
Affiliation at date of Creation: University of Alaska Fairbanks

***
## 0. Import Python Libraries

This code imports the necessary libraries used for the calculations and plotting. 

In [28]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import lpmv

***
## 1. Set constants

Set universal constants. 

In [2]:
g_TIA_min = 0.00911 # minimum tidally induced acceleration (TIA) necessary to produce the observed crustal asymmetry. 

m_M = 7.3476 * 10**22 # mass of the Moon in kg.
m_E = 5.9722 * 10**24 # mass of the Earth in kg.
G   = 6.6743 * 10**(-11) # gravitational constant; units of [ m^3 / (kg s^2) ]
r_E = 6,371 * 10**3 # radius of the Earth in meters. 

Set the parameter space for exploration. 

In [3]:
radii = np.arange(10, 51, 1) * 1000 # set up radii in kilometers; 10,000 to 50,000 in steps of 1 km. 
lagAngle = np.arange(3, 46, 1) # set up tidal lag angles to explore; from current (3 degrees) to theoretical maximum (45). 
N = 5 # maximum degree to use in the approximation. 

Calculate love numbers. 

[info about calculation method] 

In [ ]:
### NEEDS TESTING ###
def loveNumberCalc(): 


    
    return lN

In [ ]:
k_j = loveNumberCalc()

In [39]:
### NEEDS TESTING ###
def legendrePolynomialDerivative(gamma, j):
    # Function to get the derivative of the legendre polynomial. 
    # This was taken from Pou et al. [2022] (Tidal constraints on the Martian Interior). 
    # Ultimately, this should get replaced with code that can get any lPD. 

    # Convert gamma from degrees to radians. 
    rad = np.deg2rad(gamma)
    
    if j == 2:
        lPD = -(3./2.) * np.sin(2.*rad)
    elif j == 3:
        lPD = -(3./8.) * ( np.sin(rad) + 5.*np.sin(3.*rad) )
    elif j == 4:
        lPD = -(5./16.) * ( 2.*np.sin(2.*rad) + 7.*np.sin(4.*rad) )
    elif j == 5:
        lPD = -(15./128.) * ( 2.*np.sin(rad) + 7.*np.sin(3.*rad) + 21.*np.sin(5.*rad) )

    # # Get the legendre polynomial. 
    # x_value = np.cos(gamma)
    # lP = lpmv(0, j, x_value)

    # # Take the derivative of the legendre polynomial. 
    # lPD 

    return lPD

In [50]:
### NEEDS TESTING ###
from scipy.special import legendre
def legendrePolynomialDerivative_v2(gamma, j):
    # Function to get the derivative of the legendre polynomial. 
    # This was taken from Pou et al. [2022] (Tidal constraints on the Martian Interior). 
    # Ultimately, this should get replaced with code that can get any lPD. 
    # https://stackoverflow.com/questions/42153202/getting-the-derivatives-of-legendre-polynomials-in-python

    # Get the legendre polynomial. 
    poly = legendre(j)

    # Take the derivative of the legendre polynomial. 
    polyd = poly.deriv()
    print(f"polys = {polyd}")
    
    # Evaluate the derivative of the legendre polynomial. 
    rad = np.deg2rad(gamma) # convert from degrees to radians. 
    x_value = np.sin(rad)
    evald = np.polyval(polyd, x_value)

    return evald

In [ ]:
### NEEDS TESTING ###
from scipy.special import legendre_p
def legendrePolynomialDerivative_v3(gamma, j):
    # Function to get the derivative of the legendre polynomial. 
    # This was taken from Pou et al. [2022] (Tidal constraints on the Martian Interior). 
    # Ultimately, this should get replaced with code that can get any lPD. 
    # https://stackoverflow.com/questions/42153202/getting-the-derivatives-of-legendre-polynomials-in-python

    # j - degre
    # gamma - angle

    
    lPD = legendre_p(j, 

    # Get the legendre polynomial. 
    
    poly = legendre(j)

    # Take the derivative of the legendre polynomial. 
    polyd = poly.deriv()
    print(f"polys = {polyd}")
    
    # Evaluate the derivative of the legendre polynomial. 
    rad = np.deg2rad(gamma) # convert from degrees to radians. 
    x_value = np.sin(rad)
    evald = np.polyval(polyd, x_value)

    return lPD

In [51]:
lPD = legendrePolynomialDerivative(3, 2)
lPD_v2 = legendrePolynomialDerivative_v2(3,2)
print(lPD, lPD_v2)
lPD = legendrePolynomialDerivative(2, 2)
lPD_v2 = legendrePolynomialDerivative_v2(2,2)
print(lPD, lPD_v2)
lPD = legendrePolynomialDerivative(30, 2)
lPD_v2 = legendrePolynomialDerivative_v2(30,2)
print(lPD, lPD_v2)
lPD = legendrePolynomialDerivative(30, 3)
lPD_v2 = legendrePolynomialDerivative_v2(30,3)
print(lPD, lPD_v2)

polys =  
3 x
-0.1567926949014802 0.1570078687288315
polys =  
3 x
-0.10463471061618795 0.1046984901075029
polys =  
3 x
-1.299038105676658 1.4999999999999998
polys =      2
7.5 x - 1.5
-2.0625 0.37499999999999933


np.float64(0.1570078687288315)

In [52]:
from scipy.special import legendre_p


In [54]:
tempy = legendre_p(2, 0, diff_n = 0)
tempy

array([-0.5])

In [56]:
# New attempt
from scipy.special import lpmv


In [58]:
theta = np.cos(3)
degree = 2

r = lpmv(0, degree, np.cos(theta))
r = lpmv(0, 2, 3)
print(r)

13.0


***
# 2.0 Calculate the Tidally Induced Acceleration

Define several important functions. 

In [4]:
### NEEDS TESTING ###
def meanMotionCalc(G, m_p, m_s, r):
    # Function to calculate the mean motion. 
    # n = sqrt( G(m_p+m_s) / r )
    # n - mean motion
    # G - gravitational constant
    # m_p - mass of the primary
    # m_s - mass of the secondary
    # r - orbital radius

    n = np.sqrt( G*(m_p+m_s) / r )
    
    return n

In [5]:
n = meanMotionCalc(G, m_E, m_M, radii)
n

array([200874.72545544, 191526.53584675, 183372.69727434, 176178.78883679,
       169770.12888609, 164013.52652917, 158805.41420005, 154063.88156865,
       149723.18035999, 145729.84256529, 142039.88053853, 138616.72977915,
       135429.7122744 , 132452.87156406, 129664.07772715, 127044.33136004,
       124577.21628773, 122248.46484956, 120045.60937827, 117957.7003769 ,
       115975.07681509, 114089.17752355, 112292.38527   , 110577.89702807,
       108939.61539312, 107372.05718808, 105870.27613337, 104429.79709239,
       103046.55989917, 101716.87116043, 100437.36272772,  99204.9557756 ,
        98016.82961274,  96870.39450634,  95763.26792337,  94693.25369235,
        93658.32367058,  92656.60156844,  91686.34863717,  90745.95097146,
        89833.908216  ])

In [25]:
### NEEDS TESTING ###
def secularAccelerationCalc(m_p, m_s, n, N, gamma, A, r):
    # Function to calculate the secular acceleration. 
    # s = -3/2 n^2 alpha [sum from j=2 to N of ( k_j * F_j(gamma) * (A/r) ^ (2j+1) ) ]
    # s - secular acceleration; value output. 
    # n - mean motion; this can be a scalar or a vector. 
    # alpha - constant given by the mass of the secondary divided by the mass of the primary. 
    # N - highest degree to calculate. 
    # k_j - tidal love numbers. 
    # F_j - legrendre polynomial derivative. 
    # gamma - tidal lag angle in degrees. 
    # A - radius of Earth in meters. 
    # r - orbital radius in meters; this should be a scalar. 

    # Check that the radius is given as a scalar and not a vector. 
    if not np.isscalar(r):
        print("WARNING!!!\nWARNING!!!\nWARNING!!!\n")
        print("Given radius is not a scalar. Please give the radius as a scalar.")

        return
        
    # Calculate alpha. 
    alpha = m_s / m_p

    # Calculate the summation term. 
    # summation = sum from j=2 to N of ( k_j * F_j(gamma) * (A/r)^(2j+1) )
    summation = 0.0
    for j in range(2,N+1):
        print(j)
        # k_j = loveNumberCalc()
        # F_j = legendrePolynomialDerivative()
        # temp = k_j * F_j * (A/r)**(2*j+1)
        # summation = summation + temp
    
    # Make the final calculation. 
    s = (-3./2.) * n**2.0 * alpha * summation
    
    return s

In [27]:
s = secularAccelerationCalc(m_E, m_M, n[0], N, lagAngle[0], r_E, radii[1])
s

11000
2
3
4
5


np.float64(-0.0)

In [20]:
radii

array([10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000, 18000,
       19000, 20000, 21000, 22000, 23000, 24000, 25000, 26000, 27000,
       28000, 29000, 30000, 31000, 32000, 33000, 34000, 35000, 36000,
       37000, 38000, 39000, 40000, 41000, 42000, 43000, 44000, 45000,
       46000, 47000, 48000, 49000, 50000])

In [ ]:
### NEEDS TESTING ###
def g_TIA_Calc():
    # Function to calculate the tidally induced acceleration. 
    # s - secular acceleration. 
    # r - orbital radius. 

    s = secularAccelerationCalc()

    g_TIA = s * r
    
    return g_TIA